#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = -lyices -lscip
LDFLAGS = 

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2 -lyices
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/lukasol

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/Formula.o $(OBJDIR_RELEASE)/src/Parser.o $(OBJDIR_RELEASE)/src/SCIPsolver.o $(OBJDIR_RELEASE)/src/YicesSolver.o

all: release

clean: clean_release

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/Formula.o: src/Formula.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Formula.cpp -o $(OBJDIR_RELEASE)/src/Formula.o

$(OBJDIR_RELEASE)/src/Parser.o: src/Parser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Parser.cpp -o $(OBJDIR_RELEASE)/src/Parser.o

$(OBJDIR_RELEASE)/src/SCIPsolver.o: src/SCIPsolver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SCIPsolver.cpp -o $(OBJDIR_RELEASE)/src/SCIPsolver.o

$(OBJDIR_RELEASE)/src/YicesSolver.o: src/YicesSolver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/YicesSolver.cpp -o $(OBJDIR_RELEASE)/src/YicesSolver.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release

